### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Ciarands** [lnqs/textual-image#24]
Would native Windows Support be in scope?
Wanted to use this in a TUI, but cant have a dependency that relies on termios as its UNIX only.
Thank you for the amazing work.

**Comment by lnqs** [comment]
Definitely. I'm currently doing testing of different terminals and platforms to see what has to be done to support them. Windows Terminal is on the list, as it's supposed to have Sixel support. I guess replacing termios with something else on Windows to get the terminal to raw mode shouldn't be that hard.
There's also an ioctl to get the pixel size of terminal cells that won't work on Windows, but maybe escape sequences to get that information are supported.
And then it's all about how the terminal implements Sixel rendering. I've seen varying results on different Linux terminals so far. It may work out of the box when termios and ioctl are replaced or be completely broken.

So, yes, I'll have a look at some point (probably after fixing rendering on macOS on iTerm2), but due to the third point I can't make any promises if it'll work out in the end.

**Comment by Ciarands** [comment]
Appreciate it nonetheless, even just iTerm2 on Windows would be great, emulators like Wezterm support Windows.

**Comment by j4james** [comment]
> There's also an ioctl to get the pixel size of terminal cells that won't work on Windows, but maybe escape sequences to get that information are supported.

Most sixel terminals on Windows will support `CSI 16 t` for that, or you can derive the cell size from a combination of `CSI 14 t` (the windows size in pixels) and `CSI 18 t` (the window size in characters). And on genuine VT340 emulators the cell size will be fixed at 10x20 to match the original hardware, so that's a good fallback if you can't determine the size through any other means.

**Comment by lnqs** [comment]
Things are a bit more complicated here as the cursor position after drawing Sixels is quite inconsistent between different terminal emulators.

The fix you suggested, @j4james, works fine for the Windows Terminal. And as the VT340 Programmer Reference Manual states `When sixel mode is exited, the text cursor is set to the current sixel cursor position` this behaviour seems correct to me.

However, other terminals do different things. XTerm puts the cursor below the bottom left of the image. It doesn't matter if there's a Sixel Graphics Carriage Return, a Graphics New Line or no control character at the end of the Sixel data. While can be changed by sending CSI 8452 h to have the cursor at the right of the last row of the image, that control sequence doesn't seem to be widely supported.

Another one I tested so far is iTerm2. It always adds a CRLF. In character space. Which puts the cursor below the image, but to the left of the terminal, even if the image is not aligned to the left.

I guess the best way to make it work is to always include a Graphics New Line at the end of the Sixel data and issue another control sequence to move the cursor up one line and to the right as many columns as the image is wide. This (hopefully) would help to get to the same state on most terminals. And then write bug reports for behaviour like on iTerm2.

I'll try this on some more terminals to see if it's a feasible solution.

**Comment by j4james** [comment]
> Sixels is quite inconsistent between different terminal emulators.

Yeah, sorry, I should have mentioned that. If you want broad terminal support, you really can't rely on the position of the cursor after a Sixel image has been output. And filing bug reports likely won't help that much, because a lot of terminals are deliberately ignoring the standard (I've had this argument with many of them before).

I think the only way you can be sure of consistent behavior is by saving the cursor position with `DECSC` before you begin outputting the image, and then restoring that position with `DECRC` once you're done. From there you can use relative cursor movement to place the cursor where it needs to be. The only catch is you need to output enough linefeeds to make space for the image in advance, because if the image triggers a scroll, that's going to mess up the saved cursor position.

And bear in mind that Sixel images are always a multiple of 6. So if you've got a 20px high image, you may think that'll fit in a 20px high row, but its effective height is 24px, so it can still trigger a scroll on the last row of the page. You also then need to account for an additional row of scrolling on terminals that place the cursor below the image.

> XTerm puts the cursor below the bottom left of the image

It's not as simple as that. Depending on the image size, and how that aligns with the font size, it may end up below the image, or it may end up on the last row of the image (possibly other variations as well). It'll also depend on what version of XTerm you're using - it's been through a number of different cursor positioning algorithms over the years.

> When sixel mode is exited, the text cursor is set to the current sixel cursor position

Just on this point, it's worth nothing that the text cursor is set to the *top* of the sixel cursor position when the final sixel row spans two text rows (we've tested this on a real VT340). Not many terminals handle that correctly though.

**Comment by lnqs** [comment]
> Yeah, sorry, I should have mentioned that. If you want broad terminal support, you really can't rely on the position of the cursor after a Sixel image has been output. And filing bug reports likely won't help that much, because a lot of terminals are deliberately ignoring the standard (I've had this argument with many of them before).

I get the feeling there's no way to make it work at least somewhat flawlessly in most terminals.

> I think the only way you can be sure of consistent behavior is by saving the cursor position with DECSC before you begin outputting the image, and then restoring that position with DECRC once you're done. From there you can use relative cursor movement to place the cursor where it needs to be. The only catch is you need to output enough linefeeds to make space for the image in advance, because if the image triggers a scroll, that's going to mess up the saved cursor position.

The package is printing spaces over multiple lines in the same size as the image already to have borders, padding etc. added by Rich working. So that's not an issue.

Saving and restoring works great. At least until the image is higher than the terminal window. Then the scrolling problem comes into place again. However, I guess that's still the best solution for now.

> And bear in mind that Sixel images are always a multiple of 6. So if you've got a 20px high image, you may think that'll fit in a 20px high row, but its effective height is 24px, so it can still trigger a scroll on the last row of the page. You also then need to account for an additional row of scrolling on terminals that place the cursor below the image.

With storing the cursor position not that relevant anymore, I guess. But if I go back with relative movements at some point this is a good hint, thanks.

> Just on this point, it's worth nothing that the text cursor is set to the top of the sixel cursor position when the final sixel row spans two text rows (we've tested this on a real VT340). Not many terminals handle that correctly though.

I'm starting to become curious how you got that deep into this topic :grin:

**Comment by j4james** [comment]
> The package is printing spaces over multiple lines in the same size as the image

I saw that, but I thought you might not be including enough space when there's a chance the sixel height (i.e. when rounded up to a multiple of six) could end up overrunning the expected line height.

> Saving and restoring works great. At least until the image is higher than the terminal window.

Yeah, that's a good point. But in that situation I assume your padding for Rich wouldn't be working either, in which case you're no worse off than you were before.

> I'm starting to become curious how you got that deep into this topic 😁

I was working on the Sixel implementation for Windows Terminal, and I tend to be test-driven for things like this - I like to know exactly how all the edge case are supposed to work before I implement something.

And once we were able to confirm the correct behavior on a real VT340, I thought we might be able to persuade more terminals to follow that standard, and thereby improve interoperability. Unfortunately that didn't work out as well as I'd hoped.
